RutubeVideoCollector:
  max_videos_per_category: 200
  max_videos_per_tag: 300
  min_duration: 3
  max_duration: 33
  quality: 'worst'
  audio_fps: 16000
  n_frames: 64
  frame_dimensions: (256, 256)


EmbeddingCollector:
  batch_size: 8
  image_size: 256
  image_model_path: 'microsoft/LLM2CLIP-Openai-B-16' # from huggingface
  clip_image_processor: 'openai/clip-vit-base-patch16'
  text_model_path: 'BAAI/bge-m3' # from FlagEmbedding
  sample_rate: 16000
  audio_model_path: 'openai/whisper-large-v3-turbo' # from huggingface


GraphNodeCollector:
  similarity_threshold: 0.65


ClusterCollector:
  task: "cluster" # cluster
  name_model: "data2vec_v1"
  loky_max_cpu_count: 8


TrainParamMain:
 use_device: "cuda" # cuda, cpu
 start_learning_rate: 0.00001
 name_model: 'Model3'
 list_no_include_cat: None # ['Обзоры и распаковки товаров', 'Лайфстайл', 'Недвижимость', 'Здоровье', 'Природа', 'Дизайн', 'Техника и оборудование', 'Бизнес и предпринимательство', 'Культура', 'Религия', 'Строительство и ремонт', 'Сад и огород', 'Аудиокниги', 'Еда', 'Интервью', 'Развлечения', 'Лайфхаки', 'Эзотерика', 'Охота и рыбалка', 'Наука', 'Политика', 'Психология', 'Аудио', 'Технологии и интернет', 'Красота', 'Телепередачи', 'Детям', 'Аниме', 'Хобби', 'Видеоигры', 'Юмор', 'Обучение', 'Спорт', 'Разное', 'Путешествия', 'Животные', 'Новости и СМИ', 'Мультфильмы', 'Музыка', 'Сериалы', 'Фильмы', 'Авто-мото']
 list_no_include_sub: None # ['Обзоры и распаковки товаров', 'Лайфстайл', 'Недвижимость', 'Здоровье', 'Природа', 'Дизайн', 'Техника и оборудование', 'Бизнес и предпринимательство', 'Культура', 'Религия', 'Строительство и ремонт', 'Сад и огород', 'Ауд
 num_classes: 43 # count category
 num_subclasses: 1007 # count category
 batch_size: 10
 num_workers: 0 # bug then more 0
 pin_memory: False # turn off with cpu
 num_epochs: 1
 name_optimizer: "Adam" # SGD, Adam
 val_size: 0.1
 test_size: 0.1
 seed: 17


TrainParamData2Vec:
  use_device: "cuda" # cuda, cpu
  start_learning_rate: 0.00001
  name_model: 'data2vec_v2'
  batch_size: 10
  num_workers: 0 # bug then more 0
  pin_memory: False # turn off with cpu
  num_epochs: 30
  name_optimizer: "Adam" # SGD, Adam
  val_size: 0.1
  test_size: 0.1
  seed: 17


MetricsVisualizer:
  part_sub: 13
  task: "data2vec" # main
