version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(module)s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  file:
    class: logging.FileHandler
    formatter: default
    filename: 'logs/app.log'
    encoding: utf-8
  console:
    class: logging.StreamHandler
    formatter: default
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
  uvicorn.error:
    handlers: [console]
    level: ERROR
  uvicorn.access:
    handlers: [console]
    level: INFO
root:
  handlers: [file, console]
  level: INFO
